name: Firebase Multi-Env Deploy

on:
  push:
    branches:
      - test
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'  

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.30.0-0.1.pre'
         channel: 'beta' 

      - name: Install Dependencies
        run: flutter pub get      

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Flutter web
        run: flutter build web  
  

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/test" ]; then
            firebase deploy --only hosting:test
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            firebase deploy --only hosting:staging
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            firebase deploy --only hosting:prod
          else
            echo "No matching branch, skipping deploy."
          fi
